### ISSUE TITLE
No sound - inhibits DATV Express software PTT

### ISSUE THREAD

**Issue by gm8arv** [G4GUO/DatvExpressTransmitter#4]
If "Enable audio" is unchecked in the DATV Express software, it would be helpful if it did /not/ check for microphone (sound input) at start-up.

Background: I have an odd issue with the PC where the built-in microphone is intermittent, and fails to appear as a sound device at start-up more often than not.  I've done the driver re-install but it's still intermittent. From checking it seems this is a common problem, at least with the device I have.  So even though I have Codec, Audio, Enable audio unchecked, I cannot send video alone.

Another alternative could be to add an entry to the Capture, Audio, Device name drop-down list of "No sound" or something like that - at the risk of more "I don't send sound" support calls!

(I write Delphi/Pascal otherwise I might try and contribute myself.)

Thanks!  David GM8ARV

**Comment by G4GUO** [comment]
Will be in the next release
